id: AF6C2145D
title: 'The Ambrosia of Blessings: A Prayer to the Vidyādhara of Unparalleled Kindness,
  Drodül Pawo Dorje'
type: translation
pechas:
- IA7F3F19D
- I6C483647
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:27:29.413320
  last_modified_at: 2023-01-04 11:27:29.413334
  collections:
  - Adzom Drukpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IA7F3F19D/BA1F: EE10
  I6C483647/22F5: EE10
